from unittest import TestCase


class TestMain(TestCase):
    def test_foo(self):
        self.fail()
